server:
  port: 5000
  servlet:
    context-path: /api
spring:
  mvc:
    static-path-pattern: /upload/**
  resources:
    static-locations: file:D:/desktop/自行车管理系统/server/src/main/resources/static
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/CS_05536?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

